<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', '..', 'src', 'Allure.TestingPlatform', 'package', 'build', 'Allure.TestingPlatform.props'))" />
    <Import Project="$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', '..', 'src', 'Allure.Xunit.v3', 'package', 'buildTransitive', 'Allure.Xunit.v3.props'))" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Allure.XunitV3.Examples</RootNamespace>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
        <None Include="allureConfig.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Allure.Xunit.v3\Allure.Xunit.v3.csproj" />
        <ProjectReference Include="..\..\src\Allure.Xunit.v3.Generator\Allure.Xunit.v3.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <Import Project="$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', '..', 'src', 'Allure.TestingPlatform', 'package', 'buildTransitive', 'Allure.TestingPlatform.targets'))" />
    <Import Project="$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', '..', 'src', 'Allure.Xunit.v3', 'package', 'buildTransitive', 'Allure.Xunit.v3.targets'))" />

</Project>
