"theme:workflow":
  - changed-files:
    - any-glob-to-any-file: ".github/**"

"theme:build":
  - changed-files:
    - any-glob-to-any-file:
      - "*.slnx"
      - "**/*.csproj"
      - "**/Directory.Build.props"
      - "**/Directory.Build.targets"
      - "build/**/*"
      - ".gitignore"

"theme:core":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.Net.Commons/**"
      - "tests/Allure.Net.Commons.Tests/**"

"theme:xunit":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.Xunit/**"
      - "examples/Allure.Xunit.Examples/**"
      - "tests/Allure.Xunit.Tests/**"

"theme:nunit":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.NUnit/**"
      - "examples/Allure.NUnit.Examples/**"
      - "tests/Allure.NUnit.Tests/**"

"theme:specflow":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.SpecFlow/**"
      - "tests/Allure.SpecFlow.Tests/**"
      - "tests/Allure.SpecFlow.Tests.Samples/**"

"theme:reqnroll":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.Reqnroll/**"
      - "tests/Allure.Reqnroll.Tests/**"
      - "tests/Allure.Reqnroll.Tests.Samples/**"

"theme:mtp":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.TestingPlatform/**"
      - "tests/Allure.TestingPlatform.Tests/**"

"theme:xunit.v3":
  - changed-files:
    - any-glob-to-any-file:
      - "src/Allure.Xunit.v3/**"
      - "src/Allure.Xunit.v3.Generator/**"
      - "tests/Allure.Xunit.v3.Tests/**"
