<Project>
    <!-- Common metadata -->
    <PropertyGroup>
        <Version>2.15-SNAPSHOT</Version>
        <Company>Qameta Software</Company>
        <RepositoryUrl>https://github.com/allure-framework/allure-csharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <!-- Common build properties -->
    <PropertyGroup>
        <LangVersion>12</LangVersion>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <ArtifactsPath>$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), 'artifacts'))</ArtifactsPath>
    </PropertyGroup>

    <!-- Signing properties -->
    <PropertyGroup>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), 'build', 'identity.snk'))</AssemblyOriginatorKeyFile>
    </PropertyGroup>
</Project>