<Project>
    <!-- Common metadata -->
    <PropertyGroup>
        <Version>3.0-SNAPSHOT</Version>
        <Company>Qameta Software</Company>
        <RepositoryUrl>https://github.com/allure-framework/allure-csharp</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <!-- Common packaging properties -->
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <WarnOnPackingNonPackableProject>true</WarnOnPackingNonPackableProject>
    </PropertyGroup>

    <!-- Common build properties -->
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <CheckEolTargetFramework>false</CheckEolTargetFramework>
        <UseArtifactsOutput>true</UseArtifactsOutput>
        <ArtifactsPath>$([MSBuild]::NormalizeDirectory('$(MSBuildThisFileDirectory)', 'artifacts'))</ArtifactsPath>
    </PropertyGroup>

    <!-- Signing properties -->
    <PropertyGroup>
        <!-- Signing is opt-in -->
        <SignAssembly>false</SignAssembly>
        <AssemblyOriginatorKeyFile>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', 'build', 'identity.snk'))</AssemblyOriginatorKeyFile>
    </PropertyGroup>
</Project>