<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Allure.Xunit.v3</PackageId>
        <AssemblyName>Allure.Xunit.v3.reporters</AssemblyName>
        <RootNamespace>Allure.Xunit</RootNamespace>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Authors>grootstebozewolf</Authors>
        <Description>Create beautiful reports from your xUnit.net v3 tests.</Description>
        <PackageIcon>Allure-X-Color.png</PackageIcon>
        <PackageTags>$(PackageTags) xunit xunitv3</PackageTags>

        <!-- This assembly can't be signed becasue of Lib.Harmony -->
        <SignAssembly>false</SignAssembly>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="AllureMessageSink.cs" />
        <Compile Remove="AllureXunitFacade.cs" />
        <Compile Remove="AllureXunitPatcher.cs" />
        <Compile Remove="AllureXunitTestData.cs" />
        <Compile Remove="ComposedMessageSink.cs" />
        <Compile Remove="AllureXunitConfiguration.cs" />
        <Compile Remove="TypeExtensions.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="../../img/Allure-X-Color.png" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.4.2" PrivateAssets="all" />
        <PackageReference Include="xunit.v3.runner.common" Version="3.2.2" PrivateAssets="all" IncludeAssets="compile;build" />
        <PackageReference Include="xunit.v3.runner.utility" Version="3.2.2" PrivateAssets="all" IncludeAssets="compile;build" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Allure.Net.Commons\Allure.Net.Commons.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="build\" />
    </ItemGroup>

</Project>
