<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
            Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <!-- Don't compile samples as a part of test projects -->
        <DefaultItemExcludes>$(DefaultItemExcludes);Samples/**/*</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Samples/**/*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>