<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
            Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <!-- Don't compile samples as a part of test projects -->
        <DefaultItemExcludes>$(DefaultItemExcludes);@(AllureSample)</DefaultItemExcludes>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <PropertyGroup>
        <!-- The list of Allure properties used by the sample runner. -->
        <Allure_CompilerVisibleProperties>
            Allure_LocalNugetRepository;
            Allure_ResultsDirectoryFormat;
            Allure_SampleConfiguration;
            Allure_SampleSolutionDir;
            Allure_SampleSolutionName;
            Allure_SampleSolutionPath;
            Allure_SampleSelectedTargetFramework;
            Allure_SampleSupportedTargetFrameworks;
        </Allure_CompilerVisibleProperties>

        <!-- Put Allure properties in a single line and replaces the separator to ':'.
         Otherwise, the value won't be picked up by *.GeneratedMSBuildEditorConfig.editorconfig, which is an ini file.
         Roslyn will then make them accessible by source generators.
         AllureMsbuildPropsGenerator will pass them to the compilation making them consumable by the sample runner -->
        <Allure_PropertyNames>$(Allure_CompilerVisibleProperties.Replace('%0D', '').Replace('%0A', '').Replace(' ', '').Replace(';', ':'))</Allure_PropertyNames>

        <!-- The default project directory containing the samples to test. -->
        <Allure_SamplesDirectory>$([MSBuild]::NormalizeDirectory('$(MSBuildProjectDirectory)', 'Samples'))</Allure_SamplesDirectory>
        <Allure_SamplesPattern>$([MSBuild]::Unescape('$([MSBuild]::NormalizePath('$(Allure_SamplesDirectory)', '**', '*'))'))</Allure_SamplesPattern>
    </PropertyGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="Allure_PropertyNames" />
        <CompilerVisibleProperty Include="$(Allure_CompilerVisibleProperties)" />
        <CompilerVisibleItemMetadata Include="AdditionalFiles" MetadataName="Allure_ProjectSuffix" />
    </ItemGroup>

    <ItemGroup>
        <AllureSample Include="$(Allure_SamplesPattern)">
            <ProjectSuffix>$([System.Text.RegularExpressions.Regex]::Replace('$([MSBuild]::MakeRelative('$(Allure_SamplesDirectory)', '%(FullPath)'))', '[\\/\.].*', ''))</ProjectSuffix>
        </AllureSample>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..', 'build', 'Allure.Build.Tasks', 'Allure.Build.Tasks.csproj'))">
            <IncludeAssets>Runtime;Build;Native;contentFiles;Analyzers</IncludeAssets>
            <PrivateAssets>All</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

</Project>