<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))"
            Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />

    <UsingTask
        TaskName="Allure.Build.Tasks.GenerateSampleSolution"
        AssemblyFile="$([MSBuild]::NormalizePath($(IntermediateOutputPath), 'Allure.Build.Tasks.dll'))"/>

    <PropertyGroup>

        <!-- Default configuration may be unset in Directory.Build.props.
         Setting the default value here. -->
        <Allure_SampleConfiguration
            Condition=" '$(Allure_SampleConfiguration)' == '' ">$(Configuration)</Allure_SampleConfiguration>

        <_Allure_SampleSolutionPath>$(
            [MSBuild]::NormalizePath(
                '$(Allure_SampleSolutionDir)',
                '$(Allure_SampleSolutionName).slnx'
            )
        )</_Allure_SampleSolutionPath>

    </PropertyGroup>

    <!-- At this point, all AllureSample items must be already defined.
     We're converting them to AdditionalFiles items to make them visible
     by the source generators. Only items with ProjectSuffix metadata set
     are converted. -->
    <ItemGroup>

        <AdditionalFiles
            Include="@(AllureSample)"
            Allure_ProjectSuffix="%(ProjectSuffix)"/>

    </ItemGroup>

    <Target Name="Allure_GenerateTestSamples"
            AfterTargets="CopyFilesToOutputDirectory"
            Condition=" '@(AllureSample)' != '' ">

        <PropertyGroup>
            <_Allure_BuildTasksProject>$(
                [MSBuild]::NormalizePath(
                    '$(MSBuildThisFileDirectory)',
                    '..',
                    'build',
                    'Allure.Build.Tasks',
                    'Allure.Build.Tasks.csproj'
                )
            )</_Allure_BuildTasksProject>
        </PropertyGroup>

        <MSBuild
            Projects="$(_Allure_BuildTasksProject)"
            Targets="Restore;Build"
            BuildInParallel="$(BuildInParallel)"
            Properties="Configuration=Release">

            <Output TaskParameter="TargetOutputs" ItemName="AllureBuildTasksAssembly" />

        </MSBuild>

        <Copy
            SourceFiles="@(AllureBuildTasksAssembly)"
            DestinationFolder="$(IntermediateOutputPath)"
            SkipUnchangedFiles="true" />

        <Allure.Build.Tasks.GenerateSampleSolution
            SampleSources="@(AllureSample)"
            SamplePackageReferences="@(SamplePackageReference)"
            SampleProjectReferences="@(SampleProjectReference)"
            SampleSolutionDir="$(Allure_SampleSolutionDir)"
            SampleSolutionName="$(Allure_SampleSolutionName)"
            SampleSolutionPath="$(_Allure_SampleSolutionPath)"
            SampleTargetFrameworks="$(Allure_SampleSupportedTargetFrameworks)"
            LocalNugetRepository="$(Allure_LocalNugetRepository)" />

        <CallTarget
            Targets="Allure_BuildTestSamples"
            Condition=" '$(Allure_PreBuildTestSamples)' == 'true' "/>

    </Target>

    <Target Name="Allure_BuildTestSamples"
            Condition=" '@(AllureSample)' != '' ">

        <MSBuild
            Projects="$(_Allure_SampleSolutionPath)"
            Targets="Restore;Build"
            BuildInParallel="$(BuildInParallel)"
            Properties="Configuration=$(Allure_SampleConfiguration)" />

    </Target>

    <Target Name="Allure_RunTestSamples"
            Condition=" '@(AllureSample)' != '' ">

        <ItemGroup>
            <AllureSampleResultDirectory
                Include="@(
                    AllureSample -> '$(
                        [System.String]::Format(
                            '$(Allure_SampleResultsDirectoryFormat)',
                            '%(AllureSample.ProjectSuffix)'
                        )
                    )'
                )"/>
        </ItemGroup>

        <RemoveDir Directories="@(AllureSampleResultDirectory)" />

        <MSBuild
            Projects="$(_Allure_SampleSolutionPath)"
            Targets="VSTest"
            BuildInParallel="$(BuildInParallel)"
            Properties="Configuration=$(Allure_SampleConfiguration)" />

    </Target>

    <Target Name="Allure_CleanTestSamples"
            BeforeTargets="CoreClean"
            Condition="Exists('$(_Allure_SampleSolutionPath)')">

        <MSBuild
            Projects="$(_Allure_SampleSolutionPath)"
            Targets="Clean"
            BuildInParallel="$(BuildInParallel)"
            Properties="Configuration=$(Allure_SampleConfiguration)"
            Condition=" Exists('@(AllureSampleSolution)') "
            ContinueOnError="True" />

    </Target>

    <Target Name="Allure_DeleteTestSamples">

        <PropertyGroup>
            <Allure_SampleProjectBinFormat>$(
                [MSBuild]::NormalizeDirectory(
                    '$(ArtifactsPath)',
                    'bin',
                    '$(Allure_SampleSolutionName).{0}'
                )
            )</Allure_SampleProjectBinFormat>

            <Allure_SampleProjectObjFormat>$(
                [MSBuild]::NormalizeDirectory(
                    '$(ArtifactsPath)',
                    'obj',
                    '$(Allure_SampleSolutionName).{0}'
                )
            )</Allure_SampleProjectObjFormat>
        </PropertyGroup>

        <ItemGroup>
            <AllureSampleProjectOutputDirectory
                Include="@(
                    AllureSample -> '$(
                        [System.String]::Format(
                            '$(Allure_SampleProjectBinFormat)',
                            '%(AllureSample.ProjectSuffix)'
                        )
                    )'
                )"/>
            <AllureSampleProjectOutputDirectory
                Include="@(
                    AllureSample -> '$(
                        [System.String]::Format(
                            '$(Allure_SampleProjectObjFormat)',
                            '%(AllureSample.ProjectSuffix)'
                        )
                    )'
                )"/>
        </ItemGroup>

        <RemoveDir Directories="@(AllureSampleProjectOutputDirectory)" />
        <RemoveDir Directories="$(Allure_SampleSolutionDir)" />
    </Target>
</Project>