<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
            Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <!-- Don't compile samples as a part of test projects -->
        <DefaultItemExcludes>$(DefaultItemExcludes);Samples/**/*</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
        <AllureSample Include="Samples/**/*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), '..', 'build', 'Allure.Build.Tasks', 'Allure.Build.Tasks.csproj'))">
            <Private>True</Private>
        </ProjectReference>
    </ItemGroup>

</Project>