<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Allure.SpecFlow\Allure.SpecFlow.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="allureConfigStepArguments.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="allureConfig.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="allureConfigWithInvalidRegex.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
