<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <IsTestProject>false</IsTestProject>
    <AspectInjector_Enabled>false</AspectInjector_Enabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Core" Version="1.35.2" />
    <PackageReference Include="TUnit.Assertions" Version="1.35.2" />
  </ItemGroup>

</Project>
