<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <Allure_TestingPlatform>MicrosoftTestingPlatform</Allure_TestingPlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.35.2" />
  </ItemGroup>

  <ItemGroup>
    <SamplePackageReference Include="Xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectUnderTest
        Include="../../src/Allure.Xunit.v3/Allure.Xunit.v3.csproj"
        AnalyzerProjects="../../src/Allure.Xunit.v3.Generator/Allure.Xunit.v3.Generator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AllureSample Update="TestPlans/Samples/RuntimeGuard.cs" Properties="Allure_GenerateXunitEntryPoint=false" />
    <AllureSample Update="Generator/Samples/ApplyAttributeDisabled.cs" Properties="Allure_ApplyXunitAttribute=false" />
    <AllureSample Update="Generator/Samples/SelfRegistrationDisabled.cs" Properties="Allure_XunitEnableSelfRegistration=false" />
    <AllureSample Update="Generator/Samples/CustomRunnerReporter.cs" Properties="Allure_XunitEnableSelfRegistration=false" />
    <AllureSample Update="Generator/Samples/CustomStartupObject.cs" Properties="Allure_XunitEnableSelfRegistration=false;StartupObject=Allure.Xunit.v3.Tests.Samples.Generator.CustomStartupObject.Program" />
    <AllureSample Update="Generator/Samples/RunnerHelper.cs" Properties="StartupObject=Allure.Xunit.v3.Tests.Samples.Generator.RunnerHelper.Program" />
  </ItemGroup>

  <ItemGroup>
    <SampleProperty Include="UseMicrosoftTestingPlatformRunner" Value="true" />
    <SampleProperty Include="EmitCompilerGeneratedFiles" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../build/Allure.Build.SourceGenerators/Allure.Build.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Allure.Testing/Allure.Testing.csproj" />
  </ItemGroup>

</Project>
