<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>

    <!-- Required by [InternalsVisibleTo] -->
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.61.29" />
    <PackageReference Include="TUnit.Mocks" Version="1.61.29" />
    <PackageReference Include="TUnit.Mocks.Assertions" Version="1.61.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Allure.TestingPlatform/Allure.TestingPlatform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- For AllureDataConsumerTests.ShouldHaveVersionFromRootDirectoryProps -->
    <None Include="../../Directory.Build.props" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>