<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Frameworks" Version="7.0.1" />
    <PackageReference Include="NuGet.Versioning" Version="7.0.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.1" />
  </ItemGroup>

</Project>
