<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.65.68" />
    <PackageReference Include="TUnit.Mocks" Version="1.65.68" />
    <PackageReference Include="TUnit.Mocks.Assertions" Version="1.61.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Allure.Net/Allure.Net.csproj" />
  </ItemGroup>

</Project>
