<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.35.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Allure.Net/Allure.Net.csproj" />
  </ItemGroup>

</Project>