<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Adds basic support for Microsoft Testing Platform frameworks. Reference a framework-specific package to get the most from Allure.</Description>
        <PackageTags>$(PackageTags) mtp testingplatform microsofttestingplatform</PackageTags>
        <PackageIcon>Allure-Color.png</PackageIcon>
        <Nullable>enable</Nullable>
        <AspectInjector_Enabled>false</AspectInjector_Enabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Platform" Version="2.3.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Allure.Net.Sdk\Allure.Net.Sdk.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\img\Allure-Color.png" Pack="true" PackagePath="\" />
        <None Include="README.md" Pack="true" PackagePath="\" />
        <None Include="package\**\*" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
