<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.61.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Allure.Net.Sdk/Allure.Net.Sdk.csproj" />
  </ItemGroup>

</Project>
