name: "Verify type labels"

on:
  pull_request:
    types: [ labeled, unlabeled ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: baev/match-label-action@master
        with:
          allowed: 'type:bug,type:new feature,type:improvement,type:dependencies,type:internal,type:invalid'
