name: Test

env:
  SOLUTION_PATH: allure-csharp.slnx
  BUILD_CONFIGURATION: 'Release'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
      - 'hotfix-*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup .NET Core SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            3.1.x
            10.0.x

      - name: 'Restore packages'
        run: |
          dotnet restore ${{ env.SOLUTION_PATH }}

      - name: 'Build solution using dotnet'
        run: |
          dotnet build ${{ env.SOLUTION_PATH }}\
            --no-restore\
            --configuration ${{ env.BUILD_CONFIGURATION }}\
            -p:Allure_TestTargetVersion=SNAPSHOT\
            -p:Allure_PreRunTestingFlow=true

      - name: Create NuGet packages
        run: |
          dotnet pack ${{ env.SOLUTION_PATH }}\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}

      - name: Build test samples
        run: |
          dotnet msbuild ${{ env.SOLUTION_PATH }}\
            -t:Allure_BuildTestSamples\
            -p:Allure_SampleConfiguration=${{ env.BUILD_CONFIGURATION }}

      - name: 'Run test samples'
        run: |
          dotnet msbuild ${{ env.SOLUTION_PATH }}\
            -t:Allure_RunTestSamples\
            -p:Allure_SampleConfiguration=${{ env.BUILD_CONFIGURATION }}

      - name: 'Run tests'
        run: |
          dotnet test ./tests/Allure.Net.Commons.Tests\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}
          dotnet run --project ./tests/Allure.NUnit.Tests\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}
          dotnet run --project ./tests/Allure.Xunit.Tests\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}
          dotnet test ./tests/Allure.SpecFlow.Tests\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}
          dotnet test ./tests/Allure.Reqnroll.Tests\
            --no-restore\
            --no-build\
            --configuration ${{ env.BUILD_CONFIGURATION }}
